import { normalizeMemoryRecord, type MemoryRecord } from '../memoryRecord';

export const personalMemoryRecords: MemoryRecord[] = [
  normalizeMemoryRecord({
    id: 'mem_launch_may_anxiety_scope_delay',
    sourceType: 'notion',
    sourceRef: 'notion://launch-journal/may',
    createdAt: '2026-05-01T09:00:00.000Z',
    observedAt: '2026-05-01',
    rawText:
      'Felt anxious before shipping the memory import demo, so I expanded scope with graph filters and extra polish. Launch slipped by two days.',
    summary: 'Anxiety before the memory import demo led to graph filter scope expansion and a two-day launch delay.',
    memoryType: 'decision',
    emotionTags: ['anxiety', 'pressure'],
    topicTags: ['launch', 'scope expansion', 'memory import'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: 'Launch delayed by two days after adding graph filters.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_launch_june_anxiety_scope_delay',
    sourceType: 'obsidian',
    sourceRef: 'obsidian://daily/2026-05-13',
    createdAt: '2026-05-13T22:00:00.000Z',
    observedAt: '2026-05-13',
    rawText:
      'Same pattern again: anxiety about the Ask My Past Self launch turned into adding onboarding examples and replay controls. The launch was delayed.',
    summary: 'Anxiety about Ask My Past Self became feature additions and delayed the launch.',
    memoryType: 'reflection',
    emotionTags: ['anxiety'],
    topicTags: ['launch', 'feature addition', 'scope expansion', 'Ask My Past Self'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: 'Launch delayed after onboarding examples and replay controls were added.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_freeze_vs_feature_addition',
    sourceType: 'markdown',
    sourceRef: 'markdown://retros/freezing-vs-features.md',
    createdAt: '2026-05-20T18:00:00.000Z',
    observedAt: '2026-05-20',
    rawText:
      'When anxiety spikes I either freeze or add features instead of deciding what to cut. The feature-addition branch keeps postponing launches.',
    summary: 'Anxiety creates a freeze-vs-feature-addition choice, and feature addition postpones launches.',
    memoryType: 'pattern',
    emotionTags: ['anxiety', 'avoidance'],
    topicTags: ['freeze', 'feature addition', 'launch delay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'avoided',
    outcomeText: 'Launches keep being postponed when feature addition wins over cutting scope.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_unrelated_calm_import',
    sourceType: 'paste',
    sourceRef: 'paste://calm-import-note',
    createdAt: '2026-05-22T10:00:00.000Z',
    observedAt: '2026-05-22',
    rawText: 'Calmly imported Markdown notes and verified MemoryRecord normalization.',
    summary: 'Calm Markdown import verification.',
    memoryType: 'episodic',
    emotionTags: ['calm'],
    topicTags: ['markdown', 'import'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'none',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_captured_ship_note',
    sourceType: 'mobile',
    sourceRef: 'mobile://capture/ship-note',
    createdAt: '2026-05-23T12:30:00.000Z',
    observedAt: '2026-05-23',
    rawText: 'Captured a quick note to ship the import parser before adding more UI polish.',
    summary: 'Quick captured note about shipping the import parser before more polish.',
    memoryType: 'episodic',
    emotionTags: ['resolve'],
    topicTags: ['capture', 'shipping', 'import parser'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: 'Kept the import parser scope bounded for review.',
    extractionStatus: 'manual',
  }),
];

export const insufficientPatternMemoryRecords: MemoryRecord[] = [
  normalizeMemoryRecord({
    id: 'mem_single_anxiety_scope_delay',
    sourceType: 'markdown',
    sourceRef: 'markdown://single-observation.md',
    createdAt: '2026-05-24T08:00:00.000Z',
    observedAt: '2026-05-24',
    rawText: 'Anxiety led to one feature addition and one delayed launch.',
    summary: 'A single anxiety and feature-addition launch delay observation.',
    memoryType: 'reflection',
    emotionTags: ['anxiety'],
    topicTags: ['feature addition', 'launch delay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: 'One launch was delayed.',
    extractionStatus: 'ready',
  }),
];

export const repeatedPatternWithoutOutcomeRecords: MemoryRecord[] = [
  normalizeMemoryRecord({
    id: 'mem_repeat_without_outcome_one',
    sourceType: 'notion',
    sourceRef: 'notion://launch-journal/no-outcome-1',
    createdAt: '2026-05-25T08:00:00.000Z',
    observedAt: '2026-05-25',
    rawText:
      'Anxiety before shipping made me expand scope with more replay controls and the launch slipped again.',
    summary: 'Anxiety led to scope expansion and another delayed launch, but the concrete outcome was not captured.',
    memoryType: 'decision',
    emotionTags: ['anxiety', 'pressure'],
    topicTags: ['launch', 'scope expansion', 'Decision Replay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_repeat_without_outcome_two',
    sourceType: 'obsidian',
    sourceRef: 'obsidian://daily/2026-05-26-no-outcome',
    createdAt: '2026-05-26T08:00:00.000Z',
    observedAt: '2026-05-26',
    rawText:
      'The same anxiety pattern showed up again: I added more onboarding, expanded scope, and the launch delayed again, but I failed to record the result cleanly.',
    summary: 'Repeated anxiety, scope expansion, and delayed launch pattern without a preserved outcome citation.',
    memoryType: 'reflection',
    emotionTags: ['anxiety'],
    topicTags: ['launch', 'feature addition', 'scope expansion'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    extractionStatus: 'ready',
  }),
];

export const singleSourceRepeatedMemoryRecords: MemoryRecord[] = [
  normalizeMemoryRecord({
    id: 'mem_same_source_repeat_one',
    sourceType: 'markdown',
    sourceRef: 'markdown://repeat-1.md',
    createdAt: '2026-05-18T08:00:00.000Z',
    observedAt: '2026-05-18',
    rawText: 'Anxiety about launch made me add features and delay shipping again.',
    summary: 'Launch anxiety turned into feature addition and shipping delay.',
    memoryType: 'reflection',
    emotionTags: ['anxiety'],
    topicTags: ['feature addition', 'launch delay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: 'Shipping slipped after adding more features.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_same_source_repeat_two',
    sourceType: 'markdown',
    sourceRef: 'markdown://repeat-2.md',
    createdAt: '2026-05-19T08:00:00.000Z',
    observedAt: '2026-05-19',
    rawText: 'The same anxiety pattern caused expanded scope and another delayed launch.',
    summary: 'Repeated anxiety scope expansion pattern delayed launch again.',
    memoryType: 'reflection',
    emotionTags: ['anxiety', 'pressure'],
    topicTags: ['scope expansion', 'launch delay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: 'Launch delayed again after scope expansion.',
    extractionStatus: 'ready',
  }),
];
