import { normalizeMemoryRecord, type MemoryRecord } from '../memoryRecord';

export const personalMemoryRecords: MemoryRecord[] = [
  normalizeMemoryRecord({
    id: 'mem_launch_may_anxiety_scope_delay',
    sourceType: 'notion',
    sourceRef: 'notion://launch-journal/may',
    createdAt: '2026-05-01T09:00:00.000Z',
    observedAt: '2026-05-01',
    rawText:
      '기억 가져오기 데모를 내보내기 전 불안해서 그래프 필터와 추가 다듬기를 붙였다. 결국 출시가 이틀 늦어졌다.',
    summary: '불안해서 기억 가져오기 데모 범위를 넓혔고 출시가 이틀 늦어졌다.',
    memoryType: 'decision',
    emotionTags: ['anxiety', 'pressure'],
    topicTags: ['launch', 'scope expansion', 'memory import'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: '그래프 필터를 더 붙인 뒤 출시가 이틀 늦어졌다.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_launch_june_anxiety_scope_delay',
    sourceType: 'obsidian',
    sourceRef: 'obsidian://daily/2026-05-13',
    createdAt: '2026-05-13T22:00:00.000Z',
    observedAt: '2026-05-13',
    rawText:
      '같은 패턴이 다시 나왔다. 과거의 나에게 묻기 출시가 불안해서 온보딩 예시와 결정 되짚기 제어를 더 넣었고 출시가 밀렸다.',
    summary: '과거의 나에게 묻기 출시 불안이 기능 추가로 번져 출시가 늦어졌다.',
    memoryType: 'reflection',
    emotionTags: ['anxiety'],
    topicTags: ['launch', 'feature addition', 'scope expansion', '과거의 나에게 묻기'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: '온보딩 예시와 결정 되짚기 제어를 추가한 뒤 출시가 늦어졌다.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_freeze_vs_feature_addition',
    sourceType: 'markdown',
    sourceRef: 'markdown://retros/freezing-vs-features.md',
    createdAt: '2026-05-20T18:00:00.000Z',
    observedAt: '2026-05-20',
    rawText:
      '불안이 커지면 무엇을 덜어낼지 정하지 못하고 멈추거나 기능을 더 넣는다. 기능 추가 쪽을 택하면 출시가 계속 밀린다.',
    summary: '불안하면 멈추거나 기능을 더 넣는 선택으로 빠지고 출시가 밀린다.',
    memoryType: 'pattern',
    emotionTags: ['anxiety', 'avoidance'],
    topicTags: ['freeze', 'feature addition', 'launch delay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'avoided',
    outcomeText: '범위를 덜어내기보다 기능 추가를 택하면 출시가 계속 밀린다.',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_unrelated_calm_import',
    sourceType: 'paste',
    sourceRef: 'paste://calm-import-note',
    createdAt: '2026-05-22T10:00:00.000Z',
    observedAt: '2026-05-22',
    rawText: '차분하게 Markdown 일기를 가져와 MemoryRecord 정규화와 기억 변환을 확인했다.',
    summary: '차분하게 Markdown 일기를 가져와 기억 변환을 확인했다.',
    memoryType: 'episodic',
    emotionTags: ['calm'],
    topicTags: ['markdown', 'import'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'none',
    extractionStatus: 'ready',
  }),
  normalizeMemoryRecord({
    id: 'mem_captured_ship_note',
    sourceType: 'mobile',
    sourceRef: 'mobile://capture/ship-note',
    createdAt: '2026-05-23T12:30:00.000Z',
    observedAt: '2026-05-23',
    rawText: 'UI를 더 다듬기 전에 import parser를 먼저 보내자는 빠른 일기를 남겼다.',
    summary: '더 다듬기보다 import parser를 먼저 배송하자는 빠른 기록.',
    memoryType: 'episodic',
    emotionTags: ['resolve'],
    topicTags: ['capture', 'shipping', 'import parser'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: '리뷰를 위해 import parser 범위를 작게 유지했다.',
    extractionStatus: 'manual',
  }),
];

export const insufficientPatternMemoryRecords: MemoryRecord[] = [
  normalizeMemoryRecord({
    id: 'mem_single_anxiety_scope_delay',
    sourceType: 'markdown',
    sourceRef: 'markdown://single-observation.md',
    createdAt: '2026-05-24T08:00:00.000Z',
    observedAt: '2026-05-24',
    rawText: '불안 때문에 기능을 하나 더 넣었고 출시가 한 번 늦어졌다.',
    summary: '불안과 기능 추가로 출시가 늦어진 단일 관찰.',
    memoryType: 'reflection',
    emotionTags: ['anxiety'],
    topicTags: ['feature addition', 'launch delay'],
    projectTags: ['personal-memory-ai'],
    decisionSignal: 'chosen',
    outcomeText: '출시가 한 번 늦어졌다.',
    extractionStatus: 'ready',
  }),
];
